# Generated by Django 3.2.5 on 2021-07-13 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_package_tier_id_myaccount_package_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='myaccount',
            name='stripe_customer_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
