# Generated by Django 3.2.6 on 2021-08-17 09:23

from django.conf import settings
from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='', max_length=1000)),
                ('header_image', models.ImageField(blank=True, default=events.models.get_default_header_image, null=True, upload_to=events.models.get_header_image_filepath)),
                ('industry', models.CharField(blank=True, default='', max_length=255)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('start_datetime', models.DateTimeField(default='', verbose_name='start_date')),
                ('end_datetime', models.DateTimeField(default='', verbose_name='end_date')),
                ('registrants', models.ManyToManyField(null=True, related_name='attendees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
