# Generated by Django 3.2.6 on 2021-08-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='registrants',
        ),
        migrations.AddField(
            model_name='event',
            name='max_reg',
            field=models.IntegerField(default=100),
        ),
    ]
