# Generated by Django 3.2.6 on 2021-08-29 21:51

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210829_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='header_image',
            field=models.ImageField(blank=True, default=events.models.get_default_header_image, null=True, upload_to='header_images/event_id_<django.db.models.fields.AutoField>/header_img.png'),
        ),
    ]
