# Generated by Django 3.2.6 on 2021-08-30 20:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_auto_20210830_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registrants',
            field=models.ManyToManyField(blank=True, related_name='attendees', to=settings.AUTH_USER_MODEL),
        ),
    ]
