# Generated by Django 3.2.6 on 2021-08-29 21:53

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='header_image',
            field=models.ImageField(blank=True, default=events.models.get_default_header_image, null=True, upload_to=events.models.get_header_image_filepath),
        ),
    ]
