# Generated by Django 3.2.6 on 2021-08-17 11:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_auto_20210817_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_reg',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='registrants',
            field=models.ManyToManyField(null=True, related_name='attendees', to=settings.AUTH_USER_MODEL),
        ),
    ]
