# Generated by Django 3.2.6 on 2021-08-17 11:43

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='timezone3',
            field=timezone_field.fields.TimeZoneField(choices_display='WITH_GMT_OFFSET', default='Europe/London'),
        ),
        migrations.AlterField(
            model_name='event',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='Europe/London'),
        ),
    ]
