# Generated by Django 3.2.6 on 2021-08-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20210817_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='timezone',
            field=models.CharField(blank=True, default='GMT', max_length=3),
        ),
    ]
