# Generated by Django 3.2.6 on 2021-08-17 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_event_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='event',
            name='timezone2',
        ),
    ]
