# Generated by Django 3.2.6 on 2021-08-17 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20210817_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='timezone3',
            new_name='timezone',
        ),
    ]
