# Generated by Django 3.2.5 on 2021-07-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myaccount',
            name='package_name',
            field=models.CharField(default='Free Account', max_length=50),
        ),
        migrations.AddField(
            model_name='myaccount',
            name='package_tier_id',
            field=models.IntegerField(default=1),
        ),
    ]
