# Generated by Django 3.2.5 on 2021-07-10 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210710_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myaccount',
            old_name='package_tier_id',
            new_name='package_tier',
        ),
    ]
