# Generated by Django 3.2.5 on 2021-07-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_myaccount_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='myaccount',
            name='stripe_subscription_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
