# Generated by Django 3.2.5 on 2021-07-17 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_myaccount_stripe_subscription_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myaccount',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
