# Generated by Django 3.2.5 on 2021-07-17 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_myaccount_stripe_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myaccount',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='myaccount',
            name='stripe_subscription_id',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
