# Generated by Django 3.2.5 on 2021-07-18 15:34

from django.db import migrations
import django_resized.forms
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210717_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='myaccount',
            name='profile_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default=users.models.get_default_profile_image, force_format=None, keep_meta=True, null=True, quality=0, size=[500, 500], upload_to=users.models.get_profile_image_filepath),
        ),
    ]
