# Generated by Django 3.2.5 on 2021-07-23 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_myaccount_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myaccount',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='myaccount',
            name='user_permissions',
        ),
    ]
