# Generated by Django 3.2.5 on 2021-07-29 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210723_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myaccount',
            name='username',
        ),
    ]
