# Generated by Django 3.2.5 on 2021-07-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_myaccount_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myaccount',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='myaccount',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='myaccount',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
