# Generated by Django 3.2.5 on 2021-07-30 14:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20210730_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myaccount',
            name='username',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
