# Generated by Django 3.2.5 on 2021-07-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_remove_myaccount_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='myaccount',
            name='username',
            field=models.CharField(default=0, max_length=60, unique=True),
        ),
    ]
