# Generated by Django 3.2.5 on 2021-07-31 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_remove_myaccount_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myaccount',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='myaccount',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
