# Generated by Django 3.2.5 on 2021-07-31 12:00

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20210731_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myaccount',
            name='profile_image',
            field=models.ImageField(blank=True, default=users.models.get_default_profile_image, null=True, upload_to=users.models.get_profile_image_filepath),
        ),
    ]
