# Generated by Django 3.2.5 on 2021-08-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_roles_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myaccount',
            name='job_role',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='myaccount',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='myaccount',
            name='skills',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
